### ISSUE TITLE
Possible server crash with Biomes O Plenty and Toms Mod

### ISSUE THREAD

**Issue by Redlotus99** [tom5454/Toms-Mod#10]
When generating a new chunk I seem to be getting some generation issues that cause a server crash.

The log is below.

http://pastebin.com/N2EYisNa

**Comment by tom5454** [comment]
Try reporting it on the Biomes'O'Plenty issue tracker.

**Comment by tom5454** [comment]
I implemented code to prevent crash but it can mess up some of the Tom's mod world gen objects.
