### ISSUE TITLE
World Generation missing in other dimensions

### ISSUE THREAD

**Issue by Redlotus99** [tom5454/Toms-Mod#11]
I use Aroma1997's Dimensional World that is basically considered the "Mining World" mod and the ores from this mod are not spawning there. It is usually Dim 6 and I had this issue with a few other mods that put a fix in for this. Ebon Arts, Environmental Tech and TAIGA all had this issue.

Is there a way you can set it so that world gen happens in other dimensions and or add whitelisting so we can set which dimensions world gen occurs in? Either fix would be great.

Aromas Dimensional World - https://minecraft.curseforge.com/projects/aroma1997s-dimensional-world

Some code used by Environmental Tech dev to have ores spawn in other dimensions:

http://pastebin.com/dGAQeccv

Hope that helps.

**Comment by tom5454** [comment]
Its fixed in the new 2.0.13 version.
