### ISSUE TITLE
Mapwriter - Why?

### ISSUE THREAD

**Issue by Utildayael** [tom5454/Toms-Mod#12]
Like the mod, just don't get why you have Mapwriter bundled? It's a crappy map program compared to JourneyMap and honestly, no point in doing so.

Don't take this the wrong way, just don't see the point in it. If people want a map mod they most likely already went off and got one. :)

**Comment by tom5454** [comment]
Sorry for not answering for SO long. I planned to make an adventure map in 1.7.10 I added the map because of that.

**Comment by Utildayael** [comment]
Ahhh gotcha. Thanks :)
