### ISSUE TITLE
Research table doesn't work

### ISSUE THREAD

**Issue by Dragnier** [tom5454/Toms-Mod#3]
I crafted the research table recipe, the big notebook, and the regular notebook. None of them do anything. The books don't open, the tables don't open any gui, and placing two tables next to each other doesn't do anything. I can't figure out how to get started with the mod and the "wiki" doesn't give any help.

**Comment by tom5454** [comment]
Updated wiki.

**Comment by Dragnier** [comment]
Ok, got the research table now... but how do you use it? There is no way to know what to do to research anything. No clues, no instructions, absolutely nothing. As a designer, you have to remember that no one who is going to play your mod will have any idea what to do with it. They need at least basic instructions, but what may seem basic to you is probably still too far advanced for someone who doesn't know how your mod works. You inherently understand a lot of things because you made the mod. No one else does.

I tried to do the exact same recipe you show in the wiki in my research table and nothing came up.

![untitled](https://cloud.githubusercontent.com/assets/19270499/16720855/7960d96a-4708-11e6-82df-93a5aa04dffb.png)

The only other mod I've seen with any kind of research mechanic is Thaumcraft. If you look at how that works, you might get some ideas of how to implement your version of research better. Honestly, I want to test your mod, but there is currently not enough information to do so.

**Comment by tom5454** [comment]
Do you have the big notebook linked to you? (Sneak-click on a block if not, or craft one in the crafting table)
There is a button on the bottom left corner to open up the research list.

**Comment by Dragnier** [comment]
Sneak-click doesn't work. Crafting it does though.
