### ISSUE TITLE
Power research asking for minecraft:redstone_wire

### ISSUE THREAD

**Issue by Dragnier** [tom5454/Toms-Mod#5]
![2016-07-12_05 06 02](https://cloud.githubusercontent.com/assets/19270499/16761574/b8c044c4-47ee-11e6-91b5-304ed028f25e.png)

That is not what the item is called in your inventory. Cannot research. It is simply minecraft:redstone or minecraft:redstone_block depending on what you're looking for.

![2016-07-12_05 09 09](https://cloud.githubusercontent.com/assets/19270499/16761591/cc61ab80-47ee-11e6-9e9c-9e8c61cafc5e.png)

![2016-07-12_05 09 13](https://cloud.githubusercontent.com/assets/19270499/16761595/d205bd92-47ee-11e6-9bcb-349ec157a274.png)

**Comment by tom5454** [comment]
Updated wiki.
