### ISSUE TITLE
Hammer research not working

### ISSUE THREAD

**Issue by Dragnier** [tom5454/Toms-Mod#6]
![2016-07-12_05 12 23](https://cloud.githubusercontent.com/assets/19270499/16761703/4e44f940-47ef-11e6-9057-bd82c1d74acd.png)

![2016-07-12_05 12 29](https://cloud.githubusercontent.com/assets/19270499/16761707/527fdba6-47ef-11e6-8273-5f264699c363.png)

**Comment by tom5454** [comment]
Upated wiki.
