### ISSUE TITLE
Lava pump

### ISSUE THREAD

**Issue by DanHolli** [tom5454/Toms-Mod#7]
I have actually Additions and Ender IO and I'm trying to automate a wall of generators using lava from the lava creator thing but your mod is the only one with any liquid pump and wondering if you could make one.
also I would like two more things, a bucket filler and a bucket drainer

**Comment by tom5454** [comment]
For what version of minecraft?

**Comment by DanHolli** [comment]
1.10.2

**Comment by tom5454** [comment]
Ok, it'll be in the next version.

**Comment by DanHolli123** [comment]
thanks

**Comment by DanHolli** [comment]
when will the next update be or a guess of when?

**Comment by tom5454** [comment]
Maybe this weekend. Only the gui for the fluid transposer and the recipes are missing.

**Comment by DanHolli** [comment]
if it will still work I'll just /give it to me

**Comment by DanHolli** [comment]
if it pumps lava it should use obsidian
maybe 8 obsidian around the water collector

**Comment by DanHolli** [comment]
also I don't want it to replace the lava source with a block as that will mess up the lava creating multi-block.
and the pump will need to pump the lava from 1 block below it as the lava area need to be a special block from actually additions.

**Comment by tom5454** [comment]
New version uploaded. The pump works as bc pumps, but its a LOT slower. It uses power.

**Comment by DanHolli** [comment]
trying right now!

**Comment by DanHolli** [comment]
LOVE the transposer and the pump working vertically
Thanks

**Comment by DanHolli** [comment]
maybe have the pump remove the lava?
